export const items = [
  { id: 1, nome: "Arroz", preço: 5.99, categoria: "Grãos" },
  { id: 2, nome: "Feijão", preço: 7.49, categoria: "Grãos" },
  { id: 3, nome: "Macarrão", preço: 3.29, categoria: "Massas" },
  { id: 4, nome: "Óleo de Soja", preço: 4.99, categoria: "Óleos" },
  { id: 5, nome: "Sal", preço: 1.59, categoria: "Temperos" },
  { id: 6, nome: "Açúcar", preço: 2.99, categoria: "Açúcares" },
  { id: 7, nome: "Café", preço: 8.79, categoria: "Bebidas Quentes" },
  { id: 8, nome: "Leite", preço: 3.49, categoria: "Laticínios" },
  { id: 9, nome: "Pão", preço: 2.19, categoria: "Padaria" },
  { id: 10, nome: "Carne Moída", preço: 12.99, categoria: "Carnes" },
  { id: 11, nome: "Frango", preço: 9.99, categoria: "Carnes" },
  { id: 12, nome: "Peixe", preço: 14.99, categoria: "Carnes" },
  { id: 13, nome: "Ovos", preço: 4.29, categoria: "Ovos" },
  { id: 14, nome: "Tomate", preço: 2.79, categoria: "Vegetais" },
  { id: 15, nome: "Cebola", preço: 1.99, categoria: "Vegetais" },
  { id: 16, nome: "Alho", preço: 0.99, categoria: "Temperos" },
  { id: 17, nome: "Batata", preço: 2.49, categoria: "Vegetais" },
  { id: 18, nome: "Banana", preço: 3.69, categoria: "Frutas" },
  { id: 19, nome: "Maçã", preço: 4.99, categoria: "Frutas" },
  { id: 20, nome: "Laranja", preço: 3.49, categoria: "Frutas" },
];
